### PR TITLE
Move 'time is forward' check into run.c

### LINKED ISSUE #149: Lya simulation crashing with: New timestep < old
Hello everyone, my name is Chris and I've just started a PhD with Andreu at UCL. I'm looking at simulating Lyman alpha, and I get the following error:

`[ 000006.78 ] Task 20: Time error: New timestep (0.0243902) < old (0.0243902)!`

This error only crops up at certain starting redshifts (z=10, z=40 and z=60) and the run crashes immediately. I tried a range of sims with different box sizes and starting [redshfits shown here and the red boxes are the sims which crash.](https://imgur.com/a/yF7tR). I have attached the Options.mk and paramfiles I am using (had to convert them to .txt to upload them).

[Options.txt](https://github.com/rainwoodman/MP-Gadget/files/1417874/Options.txt)
[paramfile_gadget.txt](https://github.com/rainwoodman/MP-Gadget/files/1417875/paramfile_gadget.txt)
[paramfile_genic.txt](https://github.com/rainwoodman/MP-Gadget/files/1417876/paramfile_genic.txt)

Is this an issue or am I doing something wrong? Also happy to investigate with other parameters - if you have access to hypatia I've put the sims that failed in:

`/home/chrisp/Projects/testSims/borkedJobs`

Thanks!

### PR DESCRIPTION
**Pull request by sbird**
The check that time is moving forward was prone to floating point and
other problems during simulation startup. Move this into run.c and only
use it after the first timestep completes.

Fixes #149

### CODE REVIEW

File: run.c [hunk 1]
```diff
@@ -71,6 +71,9 @@ void run(void)
 
         /*Convert back to floating point time*/
         set_global_time(exp(loga_from_ti(All.Ti_Current)));
```
Comment (rainwoodman) [inline run.c]: What if set_global_time takes the integer time instead? Then there is no rounding off error.

Comment (sbird) [reply run.c]: This is a little tricky (because pesky globals). We must do set_global_time before read_snapshot, because we need All.cf.a, to get the velocity units when reading the snapshot. But before we use an integer time we must do init_timebins. And before we do that we need to do setup_sync_points. I *think* there is no need for setup_sync_points to be after set_global_time...so yes, we can probably do that.

Comment (sbird) [reply run.c]: Except we must do set_global_time(1.0) in sfr_eff.c, and 1.0 may not be on the integer timeline. (also *before* we have init_timebins). That code wants cleaning up at some point...but not today

Comment (sbird) [reply run.c]: But I can do set_global_time(exp(loga_from_ti(All.Ti_Current))) instead of All.TimeInit anyway, which should get rid of the roundoff.

**Comment by rainwoodman** [comment]
Is it possible to add a test case for this?

**Comment by sbird** [comment]
Tricky - it would be a test case for init() which should be tested by the travis run. But this only appears on some machines, I think.

**Comment by sbird** [comment]
I think no: this is an integration failure that appears only on some machines (not our test machines). There is no way we can add a test for it that I can see.

**Comment by rainwoodman** [comment]
Currently set_global_time is not covered by test_timebinmgr.c. Perhaps it shall; but it depends on other things..

For unit testing we need to invert the dependency by defining a
```
TimeStepEvent
```
Where different modules can register event handlers that gets called per step..

Then in the test case no modules have been initialized and we are only testing the barebone (All.Time)...

**Comment by rainwoodman** [comment]
So this is good to merge then?

**Comment by sbird** [comment]
I was waiting for the student to confirm that it works for them, but it should be low peril if you want to merge it now.

**Comment by Plaetean** [comment]
Yes it works, the same sim that crashed earlier has been running for ~1 hour now.

**Comment by sbird** [comment]
Ok! Let's merge it when travis goes green then.
